from typing import BinaryIO, Protocol


class ObjectStorage(Protocol):
    def save(self, key: str, content: BinaryIO, content_type: str) -> str: ...
    def local_path(self, key: str): ...
    def delete(self, key: str) -> None: ...
