from typing import Protocol
from uuid import UUID

from modules.chats.models.chat_model import Chat, ChatStatus


class ChatRepositoryContract(Protocol):
    def create(self, project_id: UUID, created_by: UUID, title: str) -> Chat: ...
    def get(self, chat_id: UUID, user_id: UUID) -> Chat | None: ...
    def list_for_project(self, project_id: UUID, user_id: UUID) -> list[Chat]: ...
    def update(self, chat_id: UUID, title: str | None, chat_status: ChatStatus | None) -> Chat: ...
    def delete(self, chat_id: UUID) -> None: ...
