from typing import Protocol
from uuid import UUID

from modules.chats.models.chat_model import Chat, ChatStatus


class ChatRepositoryContract(Protocol):
    async def create_for_assistant(
        self, assistant_id: UUID, project_id: UUID, created_by: UUID, title: str
    ) -> Chat: ...
    async def get(self, chat_id: UUID, user_id: UUID) -> Chat | None: ...
    async def list_for_project(self, project_id: UUID, user_id: UUID) -> list[Chat]: ...
    async def list_for_assistant(self, assistant_id: UUID, user_id: UUID) -> list[Chat]: ...
    async def update(
        self, chat_id: UUID, title: str | None, chat_status: ChatStatus | None
    ) -> Chat: ...
    async def delete(self, chat_id: UUID) -> None: ...
