from typing import Protocol
from uuid import UUID

from modules.projects.models.project_model import Project, ProjectAccess


class ProjectRepositoryContract(Protocol):
    def create(self, owner_id: UUID, name: str, description: str | None) -> Project: ...
    def get_access(self, project_id: UUID, user_id: UUID) -> ProjectAccess | None: ...
    def list_for_user(self, user_id: UUID) -> list[ProjectAccess]: ...
    def update(
        self, project_id: UUID, name: str | None, description: str | None, update_description: bool
    ) -> Project: ...
    def delete(self, project_id: UUID) -> None: ...
