from typing import Protocol
from uuid import UUID

from modules.projects.models.project_model import Project, ProjectAccess


class ProjectRepositoryContract(Protocol):
    def create(self, owner_id: UUID, name: str, description: str | None) -> Project: ...
    def get_access(self, project_id: UUID, user_id: UUID) -> ProjectAccess | None: ...
    def list_for_user(self, user_id: UUID) -> list[ProjectAccess]: ...
    def update(
        self,
        project_id: UUID,
        name: str | None,
        description: str | None,
        update_description: bool,
    ) -> Project: ...
    def delete(self, project_id: UUID) -> None: ...
    def has_permission(
        self, project_id: UUID, user_id: UUID, feature: str, action: str = "view"
    ) -> bool: ...
    def list_members(self, project_id: UUID) -> list[dict]: ...
    def add_member(self, project_id: UUID, email: str, permissions: dict): ...
    def update_member_permissions(
        self, project_id: UUID, member_id: UUID, permissions: dict
    ): ...
    def remove_member(self, project_id: UUID, member_id: UUID): ...
